### ISSUE TITLE
Multiple spellfiles appear to be parsed incorrectly

### ISSUE THREAD

**Issue by alok** [yuki-ycino/ncm2-dictionary#1]
I use 2 spellfiles (call them `a` and `b`). My setting is `set spellfile=a,b`. This plugin appears to read that as a single file named `a,b` rather than a comma-separated list. Specifically, I get the following error:

```
[ncm2_core@yarp] dictionary on_complete: Vim(let):E484: Can't open file /usr/local/share/dict/common-words,/usr/local/share/dict/common-words,/usr/share/dict/words 
```

**Comment by yuki-yano** [comment]
Fix https://github.com/yuki-ycino/ncm2-dictionary/commit/c93b52ab0cd1a9ebe5711414c3134f4bba9be6af
